### ISSUE TITLE
로그아웃이 안된 듯한 현상이 발생합니다.

### ISSUE THREAD

**Issue by wookho** [ajkj/xe-auto_login_module#1]
다른제작자분의 로그인기록 모듈에서도 동일한 이슈가 있어 처리가 되었던 적이 있습니다.

지금 모듈을 사용하면 상단에 0개의 메시지가 도착했다는 알림이 발생을 합니다. 로그아웃을 시도 하면 로그아웃이 된 것 처럼 되지 않고 레이아웃이나 로그상태에서 보여지는 항목들이 보여집니다. 

ex)  님 반갑습니다.  <-- 로그인한 회원이 아니기 때문에 닉네임은 보이지 않고 저렇게 문구가 나오는 등 로그시 처리되어야 할 부분들이 처리되어 버립니다.

**Comment by ajkj** [comment]
운영하고 계신 사이트에서 증상은 확인했습니다
상단의 로그인창(?)에서는 로그인 된 것으로 나오는 버그가 있고 0개의 메시지가 있다는 것이 나타나는 증상 입니다. 그런데 문제는 제 환경에서 버그 재현이 가능해야 디버깅이 가능한데, 그렇지 않아서 원인을 잘 모르겠어요.

**Comment by wookho** [comment]
@ajkj 글쎄요. 어떻게 지원을 해드려야 할지요. 퍼니엑스이님의 로그인기록 모듈도 동일한 현상이 발생하여 제보 하여서 이후 패치가 된 사례가 있습니다.

**Comment by wookho** [comment]
https://www.xpressengine.com/index.php?mid=download&package_id=18905882&release_id=22754408

**Comment by ajkj** [comment]
한번 확인해보 볼게요 도움이 될것 같아요.

**Comment by ajkj** [comment]
1.0.1 버젼에서 의도치않게(?) 방어코드(버그fix)가 들어간것 같습니다. 1.0.1을 다운로드 받으시면 해결될것같습니다.
https://github.com/ajkj/xe-auto_login_module/archive/v1.0.1.zip

**Comment by wookho** [comment]
감사합니다. 잘 되네요.
