### ISSUE TITLE
pc에서 세션 제거 버튼이 안눌러집니다.

### ISSUE THREAD

**Issue by socialskyo** [ajkj/xe-auto_login_module#10]
제 레이아웃이 문제인가 싶어 레이아웃 수정을 할려고 해도 레이아웃 수정후 저장이 안됩니다.

그리고 모바일에서 제거를 눌러보니 실제 제거는 되는데 반응이 없다고 합니다.

**Comment by ajkj** [comment]
확인해보고 추가 코멘트 달게요

**Comment by ajkj** [comment]
수정했습니다.
https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.1.0

**Comment by socialskyo** [comment]
요청을 반영해주셔서 다시한번 감사드립니다.

**Comment by socialskyo** [comment]
그런데 지금 해보니 설치 에러가 나는것 같습니다. 덮어쓰기시나 다 지우고 새로 해도 에러가 납니다.
Fatal error: Can't use function return value in write context in /host/home2/podoboy/html/modules/auto_login/auto_login.controller.php on line 104

**Comment by ajkj** [comment]
죄송합니다. empty 를 잘못사용했네요. 문제를 수정한 버젼을 업로드 하였습니다.
https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.1.2

**Comment by ajkj** [comment]
아직 모듈을 교체하지 않으셨다면 최신버젼(V1.1.4)로 교체해주세요.
사용해보시고 문제가 재발하거나 다른문제가 있는지 리포팅해주시면 감사하겠습니다.
https://github.com/ajkj/xe-auto_login_module/releases

**Comment by socialskyo** [comment]
지금 까지 전혀 문제가 없습니다. 세션 버튼 제거 부터 로그인 까지요. ^^ 스마트 로그인은
openssl인가 지원해야 한다고 해서 저는 그게 잘 모르겠고, 호스팅이라 안될꺼라 생각하여 
로그인 항상으로 해놓고 쓰고 있습니다.

**Comment by ajkj** [comment]
대부분의 웹 호스팅의 경우 OpenSSL을 지원합니다.
일부 홈서버로 윈도우 환경에서 PHP를 돌리는 경우 빼고는 OpenSSL 은 거의 대부분 설치가 되어 있다고 보시면 될것 같습니다.

```
<?php
phpinfo()
```

를 이용하여 OpenSSL이 지원가능한지 알아두시면 좋을것 같습니다. 다른 모듈이나 애드온에서도 많이 사용되는 부분이에요.

**Comment by socialskyo** [comment]
어랏..그러네요. 감사합니다. 지원합니다.^^ 변경하고 사용하겠습니다.
