### ISSUE TITLE
테이블 생성시 int, bigint 형식에 사이즈 지정

### ISSUE THREAD

**Issue by prologos** [ajkj/xe-auto_login_module#11]
```
<table name="auto_login_info">
    <column name="member_srl" type="number" size="11" notnull="notnull"/>
    <column name="auto_login_token" type="char" size="64" notnull="notnull" unique="unique_key" />
    <column name="ip_address" type="varchar" size="39" notnull="notnull" />
    <column name="time_added" type="bignumber" size="8"/>
    <column name="time_max_valid_until" type="bignumber" size="8"/>
    <column name="time_last_auto_login" type="bignumber" size="8"/>
    <column name="user_agent" type="varchar" size="300"/>
</table>
```

필요한 테이블 생성시 type="number" `size="11"`, type="bignumber" `size="8"` 등으로 number, bignumber 데이터 형식에 사이즈를 지정하셨는데 이 문법때문에 mssql에서는 설치가 되지 않습니다. 꼭 필요한 부분이 아니면 사이즈 지정 부분을 제거하셔서 mssql사용자도 쉽게 설치할 수 있게 해주세요

**Comment by ajkj** [comment]
사이즈가 MSSQL에서 에러가 나는지 몰랐네요. 곧 수정된 버젼을 업로드 하겠습니다.
10분만 기다려주세요.

**Comment by ajkj** [comment]
https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.1.3 수정했습니다. 버그리포팅해주셔서 감사합니다.

**Comment by prologos** [comment]
저도 설치하려다보니 테이블 생성이 안되서 알았습니다. xe + mssql 사용자가 적어서 어쩔수 없지요 ㅠㅠ
빠른처리 감사합니다.
