### ISSUE TITLE
설치된 모듈에 들어가지지 않는군요.

### ISSUE THREAD

**Issue by choi6157** [ajkj/xe-auto_login_module#13]
좋은자료 감사합니다. 새로업데이트 버전도 설치 후 아래와 같은 문구가 뜹니다.
Fatal error: require_once(): Failed opening required '**DIR**/composer/autoload_real.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/1/choi615709/www/modules/auto_login/vendor/autoload.php on line 6

**Comment by ajkj** [comment]
빠른 설치로 업데이트 하셨나요?
빠른설치는 가끔 에러가 나는 경우 있어, 수동으로 업데이트 해보세요.
그리고 PHP 5.3.3 이상, OpenSSL이 설치되었는지 확인해 보시겠어요?

**Comment by choi6157** [comment]
답변 감사합니다. php 버전이 낮은 이유인듯합니다. php5.2.17 ^^;
