### ISSUE TITLE
모듈 미사용이 되지 않습니다.

### ISSUE THREAD

**Issue by wookho** [ajkj/xe-auto_login_module#2]
쪽지알림 창이 비로그인 시 계속 발생하여 하용을 중지하려 체크를 해제하고 설정을 눌러도 체크해제가 되지 않습니다.

**Comment by ajkj** [comment]
버그리포트 감사합니다.

https://github.com/ajkj/xe-auto_login_module/archive/v1.0.1.zip
수정하였고 XE자료실에 업로드 하였습니다.

빠르게 받아보시려면 위 링크로 다운받으세요.

**Comment by wookho** [comment]
https://github.com/ajkj/xe-auto_login_module/issues/1

이 이슈가 더 시급한거 같은데요. 요거는 함께 처리 된건가요 ?

**Comment by ajkj** [comment]
해당이슈는 처리가 되지 않은것 같습니다. 원인을 모르겠어요. 그래도 혹시나 해서 방어코드를 집어넣긴 했습니다만 도움은 되지 않을것 같습니다.

**Comment by ajkj** [comment]
#1은 #1에서 처리할게요. 이 문제 해결되고 난 후 이슈 닫아주시면 감사하겠습니다.

**Comment by wookho** [comment]
잘 처리 되었습니다. 감사합니다.
