### ISSUE TITLE
pc용 레이아웃 설정이 되지 않습니다.

### ISSUE THREAD

**Issue by wookho** [ajkj/xe-auto_login_module#3]
레이아웃 설정이 되지 않네요.

**Comment by ajkj** [comment]
버그 제보 감사합니다.

한편으로는 버그때문에 불편을 드려서 죄송하네요..

버그 수정하였습니다.

https://github.com/ajkj/xe-auto_login_module/archive/v1.0.2.zip

**Comment by wookho** [comment]
감사합니다. 잘 처리되었네요.
