### ISSUE TITLE
그룹부활의 문제가 이 자료와 연관있는지 검토 부탁드립니다.

### ISSUE THREAD

**Issue by wookho** [ajkj/xe-auto_login_module#5]
https://github.com/xpressengine/xe-core/issues/1398

위 이슈와 관련하여 1.8 업데이트 시점에 설치한 자료가 이 자료라 가능성에 대해 확인할 필요가 있어보입니다.

또한 레벨이 최대치이라 레벨변동이 없는 최고관리권한 계정의 경우도 다음날 로그인을 해 보면 준회원이 부활되어 있는 상황이 있어서요.

테스트를 위해 잠시 모듈 사용을 중단했다가 다시 사용을 하게 했는데 이후 증상이 다시 나타나지 않는 듯한 상황입니다. 물론 지금 너무 짧은 시간이라 더 모니터링 해 보아햐 할 것 같구요.

만약 이 자료와 연관된 문제라면 지금 모듈 사용으로 해 놓은 상태라 이후 재발하게 될 가능성도 보입니다.

**Comment by wookho** [comment]
증상이 나타나지 않는게 아니라 여전히 발생하고 있네요.

**Comment by ajkj** [comment]
본 모듈은 포인트쪽은 전혀 건드리지 않았는데, 일단 혹시나 하니
일단 자동로그인 모듈에 대해서 전부 재점검 해보겠습니다.

**Comment by wookho** [comment]
@ajkj 네. 시점이 이 모듈 설치 시점과 거의 맞아 떨어져서 지금 모듈 사용을 중지 하고 모니터링 중입니다.

**Comment by ajkj** [comment]
다시한번 코드를 살펴 보았는데, 따로 회원의 그룹을 수정하거나 포인트를 건드리는 부분은 없었습니다.

모듈 작동을 끄신 현재도 증상이 있으신가요?

**Comment by wookho** [comment]
@ajkj 현재는 회원들의 활동으로 그룹이 추가되거나 하는 등의 증상은 발견되지 않고 있습니다.

**Comment by wookho** [comment]
@ajkj 
한가지 더 의심스러운건 레벨이 최고라 레벨변동이 있을수 없는 회원들도 날짜가 바뀌어 다음날 로그인 하면 준회원이 추가 되어 있는 현상이 발생하여 이 자료와 연관성에 무게를 두고 있습니다.

**Comment by ajkj** [comment]
직접 증상재현 해보고 다시 코멘트 드릴게요. 조금 시간이 걸릴것 같아요. 오늘중으로 코멘트 달게요.

**Comment by ajkj** [comment]
버그를 재현해보려고 3시간동안 확인해 보았는데도 재현되지 않습니다.
포인트 모듈도 전부 확인해 보고 자동로그인 모듈도 확인해 보았는데 전부 버그 재현이 되지 않습니다.

다만 시도해보면서 각종 Cache 때문에 모듈 변경 설정이 재대로 적용되지 않는 문제가 있었습니다.
포인트 모듈쪽에서 기본설정을에 값을 넣어서 다시 설정해주시고, 관리자페이지에서 정상적으로 값이 변경되었는 확인해주세요.

그리고 모든 종류의 캐시를 reset 해보세요..
그리고 XE관리자페이지에서 Cache 재설정을 해 주시고, 다음과 같은 php 파일을 서버에 업로드 한 후에 한번 실행해주세요. XE의 cache와는 별도로 php5.5 자체의 cache인 opCode Cache를 제거하는 것입니다. 이 문제로 인해서 설정이 정상적으로 변경이 안되는 문제가 있었습니다.

```
<?php
opcache_reset();
```

![image](https://cloud.githubusercontent.com/assets/7894760/7119442/97073276-e240-11e4-85c6-d3af20e6b07c.png)

그래도 문제가 지속적으로 발생한다면, 버그의 정확한 재현과정을 알려주시면 좋겠습니다.

**Comment by wookho** [comment]
@ajkj 일단 말씀하신대로 모두 진행했습니다. 그리고 지금 자동로그인모듈 사용을 다시 재개 해 놓았으니 내일 결과를 또 알려드리도록 하겠습니다.

저희 사이트와 다르게 그룹과 그룹 사이에 레벨이 없에 바로 다음레벨에서 그룹이 바뀌게 설정되어 있네요.

**Comment by wookho** [comment]
@ajkj 말씀하신 모듈설정값이 잘 적용되지 않는 문제가 자동로그인 모듈 사용과 연관성이 있는건가요??

**Comment by ajkj** [comment]
모듈설정값이 잘 적용되지 않는 문제는 자동로그인 모듈 및 포인트 모듈과는 관계없이 xecore 또는 php 자체의 문제입니다. 버그재현 시도중 설정을 변경하여도 캐시 때문에 정상적으로 변경된 설정값이 존재하지 않는 문제가 있었습니다.

**Comment by wookho** [comment]
@ajkj 네. 알겠습니다. 만약 말씀 하신 문제가 영향을 준 것이라면 XE core에서 이슈로 다뤄야 할 부분이 아닐까 하는 생각이 드네요. 많은 시간 검토해 주신거 감사드립니다.

**Comment by wookho** [comment]
이게 관련이 있을지 아닐지 저는 잘 모르지만 그래도 한번 코멘트 해 볼게요. 지난 토요일 이상한 경험을 했는데 위키모듈 스킨이 적용되지 않은 형태로 출력이 되고 있었습니다. 그래서 이상해서 스킨설정을 한번 다시 하고 저장을 해 주니 이내 제대로 출력이 되었구요.

자동로그인모듈의 레이아웃 설정을 분명이 1단짜리 레이아웃으로 해놓았었는데 2단짜리로 설정이 바뀌어 있었습니다. 이것도 제가 다시 1단짜리로 지정하여 저장한 일이 있습니다. 토요일즈음 오후에 있어썬 일입니다.

**Comment by ajkj** [comment]
네 말씀해주신게 모두 php5 캐시 관련되서 문제입니다.
PHP5.5 + OPcode Cache를 사용하신다면 적용후 2초후에 페이지를 다시 로딩해야 설정이 적용된 값이 보이고, 가끔은 캐시가 계속남아있어 변경된것이 전혀 적용이 되지 않는 경우가 있었습니다.

현재 xe에 pr이 올라와 있어서 해결되지 않을까 싶습니다.
https://github.com/xpressengine/xe-core/pull/1379

**Comment by wookho** [comment]
오늘 하루가 지나서 또 최고관리회원 한명이 준회원(기본그룹)이 추가되어 있고 또 다른 회원이 기본그룹이 추가되어  있네요. 아무래도 자동로그인 모듈을 사용하지 않고 오래 모니터링 해 보는 방법을 선택해야 할 듯 합니다.

**Comment by wookho** [comment]
저희 사이트는 어플리케이션을 사용해서 자동로그인 모듈 기능이 정말 필요하고 유용한데 지금 문제가 생겨서 사용하지 못하는것이 너무 아쉬워요. 물론 어떤 자료에서 문제를 일으키는지 찾기 어렵지만 마지막에 설치한 이 자료를 사용 안함으로서 문제가 발생하지 않으니 우선은 이렇게 사용을 중지 할 수 밖에 없는데요.

현실적으로 어려운 이야기일 수 있는데요. 혹시 자동로그인모듈에서 이러한 현상을 나타나지 않게 보완할 수 있을 여지를 확인해 보고 싶어서요.

현재 그룹별 동시 자동로그인 설정 기능을 제거하고 모든회원에게 동일하게 설정하는 것으로 수정이 가능하면 이러한 형태로 저희 사이트에서 테스트를 해 보면 어떨까 해서 문의 드려봅니다. 물론 이것으로 테스트시 문제가 발생하지 않는다고 하여 문제점을 바로 알아내긴 어렵겠지만요....

**Comment by ajkj** [comment]
2가지 버젼을 동시에 관리하는건 어려울것 같습니다. 무엇보다도 현재 어디가 문제인지 잘 모르는 상황에서 추측으로만 수정하는건 큰 효과가 없을것 같습니다.

A/B테스트를 진행해보는건 어떨까요?
member_srl 을 기준으로 짝수는 자동로그인 모듈을 사용토록 하고, 홀수는 자동로그인 모듈을 미사용하도록(XE 기본 자동로그인 이용) 합니다.(또는 회원그룹 등을 대상으로 일부만 자동로그인을 이용하도록 변경)
자동로그인 진행시에 별도의 Debugging용 로그파일을 생성하여, 어디에서 문제가 발생하는지 확인해보면 좋을것 같습니다.
그리고 자동로그인시 별도의 기록을 남기도록 하여, 어느 시점에 문제가 발생하는제 확인하는 방법이 좋을것 같습니다.
(ex. member_srl이 짝수인 회원을 대상으로 자동로그인 모듈 실행, 자동로그인이 동작하는 모든 시점에 디버깅 로그파일을 생성합니다. 그리고 항상 그룹이 변경되었나 체크를 하여 그룹이 변경되는 시점을 잡아냅니다.)

괜찮으시다면 디버깅이 가능하도록 모듈을 수정해보겠습니다.

**Comment by wookho** [comment]
@ajkj 확인 가능하신 방법을 최대한 저희 사이트에서 지원해 드리고 싶습니다. 왜냐면 저희도 이 모듈을 사용하고 싶기 때문이죠. 테스트 기간동안 제가 회원그룹 추가되는 것을 수동으로 체크해제 해 갈 생각인데요. 이런 상황이 확인하시는데 큰 문제가 없다면 말씀하신대로 짝수와 홀수를 구분하여 비교하셔도 될 것 같습니다.

일단 최대한 지원해 드리는 방향으로 하겠습니다. 원인은 모르겠지만 일단 모듈 사용을 안하는경우 모듈 사용을 하는경우 증상 차이가 있다는 것 만 확인된 상황이라서요.

**Comment by ajkj** [comment]
그러면 A/B 테스트 및 디버깅이 가능하도록 모듈을 부분적으로 수정해볼게요. 2일내로 업로드 해 드리겠습니다.

**Comment by ajkj** [comment]
디버깅용 자료입니다.

https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.0.3-debug

설치방법
- 모듈은 그대로 덮어 씌우시면 됩니다.
- 압축파일안의 addon 폴더에 들어있는 addon은 별도의 addon으로 설치해주세요. PC/Mobile 전부 작동하도록 해 주셔야 합니다.

디버깅 안내
./files/config/ 폴더안에 auto_login_debug.php 및 auto_login_debug.module.php 파일이 생성되고 해당 파일내에 디버깅 로그가 생성됩니다.
1. 자동로그인 모듈 동작시 auto_login_debug.module.php 에 기록이 됩니다.
2. 모듈 초기화, 모듈 진행전, 모듈작동후, HTML 출력전의 4가지 상태에서 항상 회원의 group 상태를 감시합니다. 회원의 group이 변경되면 자동으로 현 시점을 auto_login_debug.php에 기록합니다.

문제발생시 해당파일 2개를
thename@requery.me 로 보내주세요. 파일 보내시기 전에 중요한 개인정보가 들어있는지 확인하시고 마스킹 해서 보내주세요.

**Comment by wookho** [comment]
@ajkj 감사합니다. 지금 설치하고 모니터링 중입니다.

**Comment by wookho** [comment]
@ajkj 회원 한명이 지금 준회원그룹이 추가되었는데요. 파일은 auto_login_debug.module.php 파일 하나만 있습니다. 우선 이것만 보내드리도록 하겠습니다.

**Comment by wookho** [comment]
@ajkj 그리고 해당회원은 회원번호가 짝수 입니다.   253692

**Comment by wookho** [comment]
@ajkj 회원전체를 자동로그인모듈 사용으로 하고 디버깅을 해야하는거 아닌지 생각이 듭니다. 코멘트 주시는대로 하겠습니다.

**Comment by ajkj** [comment]
현재까지 확인한 결과 정확한 원인 판단은 어렵습니다. 다만 /?obid=xxxxxx 라는 형태의 요청이 들어온 것으로 보아서 별도의 앱 관련 모듈을 이용하고 계시는것 같습니다.

또한 짝수 홀수 상관없이 문제가 발생하는것으로 보아 자동로그인을 진행하는 시점에 문제가 발생하는것 같네요.

auto_login_debug.php 파일은 로그인 이후에 그룹 변화가 일어난 경우만을 감지합니다. 이 파일이 존재하지 않는 것으로 보아서 자동 로그인 시점 또는 자동로그인이 생성되는 시점에 문제가 발생하는것으로 추정하고 있습니다.

현재로서는 극히 낮은 확률이긴 하지만, 사용하고 계시는 앱 모듈과 충돌이 일어나고 있지 않나 조심스레 추측하고 있습니다. 현재의 디버깅 기록으로는 앱 모듈과 자동로그인 모듈이 동시에 동작하는것으로 추정되는데요. 예전에 기억하기로는 앱이 일반적인 PC/모바일 웹브라우져랑 조금 다른 부분이 있던 것으로 기억이 하고 있습니다.(기억상으로는 Apache http library를 이용하여 특이하게 처리했던 것으로 기억하고 있습니다.)

상세한 이력 추적을 위해서는 다음 디버깅 로그를 조금 더 상세하게 출력하도록 변경 했습니다. 다음 파일로 업데이트 부탁드리겠습니다.

변경내역
- 디버깅시 Context를 통으로 저장함.
- 모든 회원을 대상으로 자동로그인을 진행함.
  https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.0.3-debug2

이용방법
기존의 ./files/config/ 폴더에 있는 auto_login_debug.php 파일과 auto_login_debug.module.php 파일은 삭제하시고, 새로운 모듈과 애드온으로 덮어씌워주세요.

문제가 발생하시면 위 파일과 함께 다음 사항을 같이 발송 부탁드립니다.
문제가 발생한 회원의 member_srl, 해당 member에 대한 해당 회원에 대해 문제를 파악하신 시점
ex)증상을 3시에 최초 발견했고, 변경시점은 11~3시로 추정

debug용 파일에는 상당히 민감한 개인정보가 포함되어 있습니다. 발송시 중요한 정보에 대해서는 마스킹 처리해서 발송해주세요.

**Comment by ajkj** [comment]
v1.0.3-debug2 보다 업그레이드 된 v1.0.3-debug3 를 로 설치 부탁드립니다.

문제의 여지가 있을지도 모르는 부분을 수정했습니다.

https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.0.3-debug3

**Comment by wookho** [comment]
@ajkj 네 감사합니다. 디버그3 로 설치했습니다.

**Comment by wookho** [comment]
@ajkj 디버그3 자료로 업로드후 그룹추가자 2명 발견하여 해당 메일 보내드렸습니다. 생성되는 파일의 용량이 너무 커서 사이트에 문제가 생길것 같아 잠시 애드온 사용을 중지 하겠습니다.

이후 코멘트 해 주시는 대로 하겠습니다.

**Comment by wookho** [comment]
@ajkj 아.. 참고로 162686    -> 2    162686  20150418091046 

위 사용자는 앱 사용자가 아닙니다. 아이폰유저로서 안드로이드앱을 설치하지 않았고 사용도 하지 않는 회원입니다.

**Comment by wookho** [comment]
한가지 추가 문의 드립니다. 저희 앱 제작시 브라우저 에이전트에 app_pomelove 라는 문자열을 삽입하여 앱으로 접속했는지 확인할때 사용하고 있는데 이 문자열이 확인되지 않고 있습니다. 수정하신 내용에 이러한 부분이 들어가 있는지 궁금합니다. 저희는 앱접속 구분하여 안내 배너를 다르게 띄워주는 것이 있는데요. 앱접속확인이 안되고 있네요. 또한 아이폰접속자를 구분하는 iphone 이라는 문자열도 확인이 되지 않네요.

**Comment by ajkj** [comment]
group 관련으로 문제가 발생하는것으로 추정하는 부분을 수정하였고, 추가적으로 디버깅 코드 부분은 경량화 하였습니다.

https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.0.3-debug4
해당 파일을 다운로드 후 이전과 같이 설치 해보시고 피드백 부탁드립니다.
(기존의 디버깅 파일은 전부 제거해주시고, 모듈 및 애드온은 덮어 씌우시면 됩니다.)

user-agent에 app_pomelove가 확인이 되지 않는다는 부분이 어디서 확인이 되지 않는다는 말씀이신가요? 자동로그인 관리페이지에서 보이지 않는다는 말씀이신가요? 디버깅 로그상으로는 ua에 app_pomelove가 정상적으로 들어가 있습니다.

해당 문제는 문제가 발행하는 부분의 스크린샷을 발송해주시면 좋을것 같습니다.

**Comment by wookho** [comment]
저희 사이트 레이아웃에 스크립트를 넣어 브라우저에이전트를 확인한 후 배너를 제어 하는 부분이 있습니다.

<시작script type="text/javascript">
var broswerInfo = navigator.userAgent;
if(broswerInfo.indexOf("app_pomelove")>-1 || broswerInfo.indexOf("iPhone")>-1){
document.getElementById("android_no").style.display="none";
document.getElementById("android_on").style.display="block";
}
</끝scrip-t-끝>

헤더에서 저단어가 검색이 되지 않는 건지 저 스크립트가 동작을 안하는건지 게시판 상.하단의 배너들이 브라우저와 상관없이 노출되는 현상이 있네요.

**Comment by ajkj** [comment]
저 문제는 자동로그인 모듈 설치 이후 발생하는 문제인가요?

**Comment by wookho** [comment]
@ajkj 새로 올려주신 자료로 설치하고 애드온 다시 활성화 했습니다.

**Comment by wookho** [comment]
ajkj 자동로그인 모듈 설치 이후 발생하는 문제는 맞는데요. 이 부분은 자동로그인 사용이 정상화 된 후 다시 확인해 보도록 하겠습니다.

**Comment by ajkj** [comment]
방금 앱 설치했는데, 정상적으로 배너가 숨겨지고 있습니다.
증상이 간헐적으로 나타나지는 않으시나요? 간헐적으로 나타나는 경우 자동로그인 모듈 문제가 아니라
JS를 통한 Dom 조작을 DOM 조작이 가능하기전에 시도해서 생기는 문제 같습니다.
다음과 같이 jQuery(document).ready(function() { ... });으로 감싸주세요.

```
jQuery(document).ready(function(){
   var broswerInfo = navigator.userAgent;
   if(broswerInfo.indexOf("app_pomelove")>-1 || broswerInfo.indexOf("iPhone")>-1){
   document.getElementById("android_no").style.display="none";
   document.getElementById("android_on").style.display="block";
}
});
```

**Comment by ajkj** [comment]
![image](https://cloud.githubusercontent.com/assets/7894760/7214415/779772ee-e5e6-11e4-99a1-018bcd4ee963.png)

**Comment by wookho** [comment]
http://pomelove.com/xe/my_pom

여기 게시판에 하단에 흔들면 랜덤으로 사진 보기가 가능하다고 배너가 나와야해요.
저도 말씀하신 코드로 수정해 보겠습니다.

**Comment by wookho** [comment]
말씀하신 코드로 교체해서는 되는게 아닌가 봅니다. 저는 레이아웃 맨 하단에 넣었습니다.

**Comment by ajkj** [comment]
당연한 소리지만 `<script> ...</script>` 사이의 코드를 교체하셔야 합니다. 그냥 통으로 삽입하시면 HTML로 노출됩니다.

**Comment by ajkj** [comment]
```
var broswerInfo = navigator.userAgent;
if(broswerInfo.indexOf("app_pomelove")>-1 || broswerInfo.indexOf("iPhone")>-1){
document.getElementById("android_no").style.display="none";
document.getElementById("android_on").style.display="block";
}
```

요 부분을

```
jQuery(document).ready(function(){
   var broswerInfo = navigator.userAgent;
   if(broswerInfo.indexOf("app_pomelove")>-1 || broswerInfo.indexOf("iPhone")>-1){
   document.getElementById("android_no").style.display="none";
   document.getElementById("android_on").style.display="block";
}
});
```

으로 교체해보세요.

**Comment by wookho** [comment]
네. 그렇군요. 말씀하신대로 해서 적용했습니다. 그런데 제가 확인한 증상은 모듈의 문서안 혹은 모듈의 상하단의 배너의 제어가 안되는 현상이구요.

게시글을 하나 작성해서 해당문구가 헤더에 포함되었는지 확인하는 스크립트를 작성해서 그 글을 접근해 보면 포함되지 않은 것으로 나옵니다. 

물론 스크린샷에 올려주신 팝업의 html은 제어가 되고 있습니다. 이게 새로운 현상이라 문의를 드려 본거에요.

**Comment by ajkj** [comment]
증상을 정확히 설명부탁드립니다.
관리자 권한으로 user-agent를 check하는 js를 게시글로 삽입했는데 user-agent가 감지되지 않는다는 말씀이신가요?

**Comment by ajkj** [comment]
어느 화면에서 어떻게 나와야 하는데, 어떻게 나오고 있다 라는 설명을 스크린샷을 포함해서 정확히 설명해 주셔야 빠르게 해결이 가능할것 같습니다.

**Comment by ajkj** [comment]
증상 또한 간헐적인지, 100% 발생하는지 알려주시면 좋겠습니다.

**Comment by wookho** [comment]
var broswerInfo = navigator.userAgent;
if(broswerInfo.indexOf("app_pomelove")>-1){
alert("앱으로 접속하셨습니다.");
}

위 스크립트를 본문에 작성해서 해당 게시물을 열람하면 알럿으로 앱으로접속하셨습니다. 라고 잘 떴었습니다. 결론적으로 본문이나 게시판 상하단에서 브라우저 헤더에 포함된 app_pomelove를 검출하지 못하는 것으로 보입니다.

그리고 저희 사이트에는 본문안에 공지사항 게시판이라던가...  상단에 안드로이드앱설치 안내 배너가 나가고 있습니다. 하지만 앱접속자에게는 사이트이용설명서 필독 안내문이 나가게 해 놓은 상황인데
지금은 앱사용자를 인식하지 못하고 있습니다. 네. 간헐적이 아닙니다. 지속적인 현상이구요.

이 현상은 제가 자동로그인 문제점이 완료되면 자동로그인 모듈은 한번 완전히 삭제해 보고 비교 예정입니다.

**Comment by wookho** [comment]
브라우저 헤더 문자열 검출 문제는 아직 코어업데이트와 모듈설치 두가지 영향을 받을 수 있으니 자동로그인모듈에서 영향을 줄수 있는 것이 없다면 일단 지금은 그냥 넘기셔도 될 거 같아요. 제가 나중에 다시 문의 드릴게요.

**Comment by ajkj** [comment]
ZAP Proxy를 이용하여 강제로 HTML에 해당 문구를 삽입했습니다.
안드로이드 4.3 기준 정상적으로 작동하고 있습니다.
![image](https://cloud.githubusercontent.com/assets/7894760/7214579/f472ffbc-e5ec-11e4-9c2c-cf034e1a07b0.png)
![image](https://cloud.githubusercontent.com/assets/7894760/7214586/1dd18fe0-e5ed-11e4-9316-34b747049532.png)

**Comment by wookho** [comment]
http://pomelove.com/xe/notice/524001

위 게시물 앱으로 접속하셔서 보시면 게시물 상단배너가 지금 안드로이드앱 설치 유도 배너가 아니고 이용설명서 필독 안내 배너로 잘 나오시나요 ?

**Comment by ajkj** [comment]
이건 자동로그인 모듈의 문제가 아닌 다른 문제입니다.
1. CSS ID Selector의 중복
HTML ID 는 중복없이 1개의 Element에만 사용해야 합니다. 동일한 ID를 2개 이상의 element에 사용시 오류가 발생합니다. 해당 페이지는 android_no android_on이 각각 2개가 중복됩니다. 본문상의 배너와 플로팅 배너에 2개가 사용되는것으로 보이네요. ID가 아닌 class로 변경하셔야 할것 같습니다.
2. DOM 조작이 불가능한 상태에서 JS DOM 조작 시도.
jQuery(document).ready(function(){ ... }); 형태로 반드시 감싸야 합니다.

```
jQuery(document).ready(function(){
   var broswerInfo = navigator.userAgent;
   if(broswerInfo.indexOf("app_pomelove")>-1 || broswerInfo.indexOf("iPhone")>-1){
   document.getElementById("android_no").style.display="none";
   document.getElementById("android_on").style.display="block";
}
}); 
```

class를 이용하시려고 하면(id를 class로 변경하셔야 하는것은 아실것 같습니다.)

```
jQuery(document).ready(function(){
   var broswerInfo = navigator.userAgent;
   if(broswerInfo.indexOf("app_pomelove")>-1 || broswerInfo.indexOf("iPhone")>-1){
   jQuery('.android_no').attr('display','none');
   jQuery('.android_on').attr('display','block');
}
}); 
```

**Comment by wookho** [comment]
어이쿠...  제가 나중에 따로 확인을 더 해보려고 있는데 이렇게 수고를 기쳐 드렸네요. 말씀하신대로 팝업애드온 모바일쪽 비활성화 하고 정상적으로 동작되는거 확인되었습니다. 쓸데없는 시간 뺐어서 죄송합니다. 조언주신 내용으로 모바일쪽에도 팝업을 띄울수 있도록 변경해 보겠습니다.

덕분에 관련없는 문제 한가지를 해결 하였네요. 감사합니다.  (여러가지 상황이 시기적으로 겹치다보니 죄송합니다.)

**Comment by wookho** [comment]
그룹이 추가되는 버그는 잡힌 것 같습니다. 감사합니다.

**Comment by ajkj** [comment]
https://github.com/ajkj/xe-auto_login_module/commit/f9fb6d61b75e2bf6352e9e42d6126fe834b14175

**Comment by ajkj** [comment]
문제가 해결된것 같아서 v1.0.3을 릴리즈 하였습니다.
내일 XE 자료실에 업로드될 v1.0.3 정식버젼으로 교체해주세요.

그리고 디버깅 애드온 및 누적된 디버깅 파일은 반드시 삭제해주세요. 보안문제와 더블어 애드온을 하나다로 더 줄이는게 성능에 좋을것 같아요.

**Comment by ajkj** [comment]
혹시나 하니 현재까지 추가적인 문제가 발생하고 있지 않나 확인해 주실수 있나요?

**Comment by wookho** [comment]
@ajkj 네. 이상없습니다. 1.0.3 로 설치해서 지금까지 아무 이상없이 잘 사용하고 있어요~
