### ISSUE TITLE
모바일 자동로그인관리 잘못된 요청

### ISSUE THREAD

**Issue by wookho** [ajkj/xe-auto_login_module#8]
재현하기가 쉬운 상황의 이벤트가 아니라 등록할까 말까 고민하다 등록합니다.

상황

구글웹뷰 업데이트 (유저에이전트의 버전이 바뀜)

1.안드로이드 앱으로 앱실행
2.자동로그인이 풀려있어어서 자동로그인 체크 후 로그인
3.이상해서 자동로그인관리 탭을 하니 잘못된 요청 알림 발생

4.PC에서 확인해 보기 위해 PC로 로그인 후 자동로그인관리 클릭시 이상없이 진입
- > 웹뷰가 업데이트 되면서 업데이트 되기 전 앱브라우저가 자동로그인으로 등록되어 있고 
      신규로 웹뷰가 업데이트 된 이후 새로 업데이트버전으로 앱이 자동로그인으로 등록되어짐 확인

5.이전버전의 앱 자동로그인 등록된 것을 삭제

6.다시 안드로이드앱 실행 후 자동로그인관리를 탭 하니 이상없이 진입되고 등록된 기기도 정상적으로 잘 보입니다.

이게 오늘 경험한 상황입니다.

**Comment by ajkj** [comment]
제보 감사합니다. 수정했습니다.
https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.0.5

**Comment by wookho** [comment]
@ajkj 이게 정상인지 저는 판단하기 어려워서 문의 남깁니다. 패치 적용한 직 후 모바일 앱으로 로그인 한다음 자동로그인관리 바로 진입하니 잘못된 요청이 나옵니다.

그래서 다시 한번 자동로그인관리를 재진입하니 정상인데요...

**Comment by ajkj** [comment]
패치 직후라면 패치가 바로 적용된 이후라서 문제가 발생한게 아닐까요?
현재 별 다른 문제점을 찾지 못했습니다.

**Comment by ajkj** [comment]
추가적으로 자동로그인의 경우 Major Version Change가 일어나는 경우에만 풀리도록 되어 있습니다.
ex) Chrome/42.0.2311.90 -> Chrome/42.9.9999.99 자동로그인이 풀리지 않음
ex) Chrome/42.0.2311.90 -> Chrome/43.9.9999.99 자동로그인이 풀림

**Comment by ajkj** [comment]
추가적으로 문제점이 발생하면 알려주세요. 최대한 수정해 보겠습니다.
