### ISSUE TITLE
같은 ip/같은 브라우저임에도 세션으로 등록 되는 문제

### ISSUE THREAD

**Issue by socialskyo** [ajkj/xe-auto_login_module#9]
회원중에 이런 경우가 있었습니다.

"로그아웃하지 않은 상태에서 사파리를 바로 종료(백그라운드 종료)해버리면 
다음번 로그인 할때 같은 아이피가 추가로 등록되는 것으로 보입니다
로그아웃하고 사파리 종료 후 접속하면 기존 등록된 아이피로 되는 것 같네요"

혹시 체크 가능 하실까요?

**Comment by ajkj** [comment]
어떠한 질문을 하시고자 하는지 잘 모르겠습니다.
자동로그인 모듈은 브라우져나 ip 를 기준으로 자동로그인을 진행하지 않습니다.
자동로그인 관리 페이지에서 보이는 브라우져나 ip는 세션 관리를 돕기 위해 보여주는게 전부입니다.

다음과 같은 경우 문제가 발생 할 수 있습니다.
1. 크롬에서 자동로그인에 체크박스 하고 로그인
(서버에서 웹브라우져에 랜덤한 쿠키를 부여하고,  해당값을 DB에 저장)
2. 쿠키 강제 삭제(크롬의 쿠키 삭제/개인정보 보호모드 등을 통해서...)

1-2까지 여러번 반복하면, 서버에는 자동로그인의 기록이 남아있는데 웹브라우져에서 쿠키 기록을 임의로 지워버릴 경우 문제가 발생하는것 같네요.

사용자가 쿠키를 강제로 지속적으로 지우는 경우까지는 생각해 보지 못했어요.

현재 이 방법에 대한 뾰족한 해결책은 없는것 같습니다.
현재로서는 자동로그인 기본 On 기능을 사용하지 않는것이 해결책 인것 같습니다.

이 부분에 대해서는 조금 더 고민을 해 보고 답변 드리겠습니다.

P.S
맥을 사용중이 아니라서 사파리 테스트는 어려울것 같네요.

**Comment by socialskyo** [comment]
잘 알겠습니다. 감사합니다.

**Comment by ajkj** [comment]
예전부터 만들어 두려고 한 스마트 자동로그인 옵션을 만들어서 해결했습니다.
https://github.com/ajkj/xe-auto_login_module/releases/tag/v1.1.0
